/**
 * In-Memory Data Store & Manager for fallback mode
 */
const bcrypt = require('bcryptjs');

let users = [
  {
    _id: 'usr_admin',
    id: 'usr_admin',
    name: 'Alex Morgan',
    email: 'admin@leadflow.ai',
    passwordHash: '$2a$10$X87oD50t.y8rY8R6wP6H1OaUvQ0uTz6J6z5b4C3v2A1b0C9d8e7f', // password123
    role: 'Admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    title: 'VP of Global Sales',
    phone: '+1 (555) 019-2834',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_sales1',
    id: 'usr_sales1',
    name: 'Sarah Chen',
    email: 'sarah.chen@leadflow.ai',
    passwordHash: '$2a$10$X87oD50t.y8rY8R6wP6H1OaUvQ0uTz6J6z5b4C3v2A1b0C9d8e7f',
    role: 'Sales',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=250&q=80',
    title: 'Senior Enterprise AE',
    phone: '+1 (555) 014-9921',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
  {
    _id: 'usr_sales2',
    id: 'usr_sales2',
    name: 'Marcus Vance',
    email: 'marcus.vance@leadflow.ai',
    passwordHash: '$2a$10$X87oD50t.y8rY8R6wP6H1OaUvQ0uTz6J6z5b4C3v2A1b0C9d8e7f',
    role: 'Sales',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    title: 'Account Executive',
    phone: '+1 (555) 017-4482',
    status: 'Active',
    createdAt: new Date().toISOString(),
  },
];

let companies = [
  {
    _id: 'cmp_1',
    id: 'cmp_1',
    name: 'Acme Global Tech',
    industry: 'Enterprise Software',
    employees: 450,
    revenue: 12500000,
    website: 'https://acmeglobaltech.com',
    email: 'contact@acmeglobaltech.com',
    phone: '+1 (800) 555-0199',
    address: '100 Technology Way, San Francisco, CA',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    _id: 'cmp_2',
    id: 'cmp_2',
    name: 'Apex Financial Services',
    industry: 'Fintech & Banking',
    employees: 1200,
    revenue: 45000000,
    website: 'https://apexfinancial.com',
    email: 'info@apexfinancial.com',
    phone: '+1 (888) 555-0144',
    address: '25 Wall Street, New York, NY',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    _id: 'cmp_3',
    id: 'cmp_3',
    name: 'Starlight BioHealth',
    industry: 'Healthcare & Biotech',
    employees: 180,
    revenue: 8200000,
    website: 'https://starlightbio.com',
    email: 'partners@starlightbio.com',
    phone: '+1 (800) 555-0177',
    address: '450 Innovation Blvd, Boston, MA',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    _id: 'cmp_4',
    id: 'cmp_4',
    name: 'Nexus Cloud Systems',
    industry: 'Cloud Infrastructure',
    employees: 650,
    revenue: 28000000,
    website: 'https://nexuscloud.io',
    email: 'sales@nexuscloud.io',
    phone: '+1 (800) 555-0123',
    address: '500 Cloud Way, Seattle, WA',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    _id: 'cmp_5',
    id: 'cmp_5',
    name: 'Omni Retail Group',
    industry: 'E-commerce & Retail',
    employees: 920,
    revenue: 34000000,
    website: 'https://omniretail.com',
    email: 'hello@omniretail.com',
    phone: '+1 (800) 555-0188',
    address: '12 Commerce Blvd, Austin, TX',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
];

let contacts = [
  {
    _id: 'cnt_1',
    id: 'cnt_1',
    firstName: 'David',
    lastName: 'Miller',
    email: 'david.miller@acmeglobaltech.com',
    phone: '+1 (555) 234-5678',
    designation: 'Chief Technology Officer',
    company: 'cmp_1',
    notes: 'Key decision maker for Q3 infrastructure overhaul.',
    createdAt: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    _id: 'cnt_2',
    id: 'cnt_2',
    firstName: 'Elena',
    lastName: 'Rostova',
    email: 'elena.r@apexfinancial.com',
    phone: '+1 (555) 876-5432',
    designation: 'VP of Operations',
    company: 'cmp_2',
    notes: 'Interested in AI CRM compliance features.',
    createdAt: new Date(Date.now() - 24 * 86400000).toISOString(),
  },
  {
    _id: 'cnt_3',
    id: 'cnt_3',
    firstName: 'Robert',
    lastName: 'Kim',
    email: 'r.kim@starlightbio.com',
    phone: '+1 (555) 345-6789',
    designation: 'Head of Procurement',
    company: 'cmp_3',
    notes: 'Requested security standard documentation.',
    createdAt: new Date(Date.now() - 19 * 86400000).toISOString(),
  },
  {
    _id: 'cnt_4',
    id: 'cnt_4',
    firstName: 'Sophia',
    lastName: 'Martinez',
    email: 'smartinez@nexuscloud.io',
    phone: '+1 (555) 987-6543',
    designation: 'Director of IT Security',
    company: 'cmp_4',
    notes: 'Approved technical evaluation scope.',
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    _id: 'cnt_5',
    id: 'cnt_5',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'jwilson@omniretail.com',
    phone: '+1 (555) 456-7890',
    designation: 'VP of Commercial Sales',
    company: 'cmp_5',
    notes: 'Wants demo for 50-person sales team.',
    createdAt: new Date(Date.now() - 9 * 86400000).toISOString(),
  },
];

let leads = [
  {
    _id: 'led_1',
    id: 'led_1',
    title: 'Enterprise AI Suite Expansion',
    value: 85000,
    status: 'Proposal',
    priority: 'High',
    source: 'LinkedIn',
    company: 'cmp_1',
    contact: 'cnt_1',
    assignedTo: 'usr_sales1',
    notes: [
      {
        id: 'n1',
        text: 'Sent customized proposal for 120 user licenses with premium SLA support.',
        author: 'Sarah Chen',
        createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      },
      {
        id: 'n2',
        text: 'Initial discovery call went exceptionally well. CTO confirmed budget authorization.',
        author: 'Alex Morgan',
        createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
      },
    ],
    expectedCloseDate: '2026-08-15',
    createdAt: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    _id: 'led_2',
    id: 'led_2',
    title: 'Fintech Compliance Workflow Integration',
    value: 120000,
    status: 'Qualified',
    priority: 'Urgent',
    source: 'Referral',
    company: 'cmp_2',
    contact: 'cnt_2',
    assignedTo: 'usr_sales1',
    notes: [
      {
        id: 'n3',
        text: 'Completed SOC2 security compliance review.',
        author: 'Sarah Chen',
        createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
      },
    ],
    expectedCloseDate: '2026-08-30',
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    _id: 'led_3',
    id: 'led_3',
    title: 'BioTech Analytics Dashboard License',
    value: 45000,
    status: 'Won',
    priority: 'Medium',
    source: 'Website',
    company: 'cmp_3',
    contact: 'cnt_3',
    assignedTo: 'usr_sales2',
    notes: [
      {
        id: 'n4',
        text: 'Contract signed! Onboarding scheduled for next Monday.',
        author: 'Marcus Vance',
        createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
      },
    ],
    expectedCloseDate: '2026-07-18',
    createdAt: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
  {
    _id: 'led_4',
    id: 'led_4',
    title: 'Multi-Cloud CRM Automation Platform',
    value: 95000,
    status: 'Contacted',
    priority: 'High',
    source: 'Cold Call',
    company: 'cmp_4',
    contact: 'cnt_4',
    assignedTo: 'usr_admin',
    notes: [
      {
        id: 'n5',
        text: 'Sent product architecture presentation to IT Director.',
        author: 'Alex Morgan',
        createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      },
    ],
    expectedCloseDate: '2026-09-01',
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    _id: 'led_5',
    id: 'led_5',
    title: 'Retail POS Lead Pipeline Migration',
    value: 62000,
    status: 'New',
    priority: 'Medium',
    source: 'Email',
    company: 'cmp_5',
    contact: 'cnt_5',
    assignedTo: 'usr_sales2',
    notes: [],
    expectedCloseDate: '2026-09-15',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

let activities = [
  {
    _id: 'act_1',
    id: 'act_1',
    userName: 'Sarah Chen',
    type: 'STATUS_CHANGE',
    description: 'Updated lead "Enterprise AI Suite Expansion" status to Proposal',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    _id: 'act_2',
    id: 'act_2',
    userName: 'Marcus Vance',
    type: 'STATUS_CHANGE',
    description: 'Closed deal "BioTech Analytics Dashboard License" as Won ($45,000)',
    createdAt: new Date(Date.now() - 14 * 3600000).toISOString(),
  },
  {
    _id: 'act_3',
    id: 'act_3',
    userName: 'Alex Morgan',
    type: 'LEAD_CREATED',
    description: 'Created new lead "Retail POS Lead Pipeline Migration"',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
  {
    _id: 'act_4',
    id: 'act_4',
    userName: 'Sarah Chen',
    type: 'NOTE_ADDED',
    description: 'Added a note to "Fintech Compliance Workflow Integration"',
    createdAt: new Date(Date.now() - 36 * 3600000).toISOString(),
  },
  {
    _id: 'act_5',
    id: 'act_5',
    userName: 'Alex Morgan',
    type: 'COMPANY_ADDED',
    description: 'Added new company "Omni Retail Group"',
    createdAt: new Date(Date.now() - 48 * 3600000).toISOString(),
  },
];

const getStore = () => ({
  users,
  companies,
  contacts,
  leads,
  activities,
});

module.exports = {
  users,
  companies,
  contacts,
  leads,
  activities,
  getStore,
};
